2024-03-26 19:48:32,431 - root - INFO - Training started at 26/03/2024 19:48:32Epoch 00020: reducing learning rate of group 0 to 7.9990e-03.
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    RETCODE = main()
  File "main.py", line 83, in main
    train_predictor()
  File "main.py", line 74, in train_predictor
    train_pred = TrainingPredictor(model=Predictor_Baseline())
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 83, in __init__
    "values": np.linspace(WARMUP_INITIAL_LR,
  File "<__array_function__ internals>", line 200, in linspace
  File "/home/bletchkey/.local/lib/python3.8/site-packages/numpy/core/function_base.py", line 121, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer
2024-03-26 21:24:05,360 - root - INFO - Training started at 26/03/2024 21:24:05
2024-03-26 21:26:07,731 - root - INFO - Training started at 26/03/2024 21:26:07
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    RETCODE = main()
  File "main.py", line 83, in main
    train_predictor()
  File "main.py", line 75, in train_predictor
    train_pred.run()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 121, in run
    self._fit()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 175, in _fit
    data = self.__test_predictor_model()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 392, in __test_predictor_model
    self.predict_from_config_type,
AttributeError: 'TrainingPredictor' object has no attribute 'predict_from_config_type'
2024-03-26 21:32:18,331 - root - INFO - Training started at 26/03/2024 21:32:18
/home/bletchkey/.local/lib/python3.8/site-packages/torch/autograd/__init__.py:251: UserWarning: Error detected in PowBackward0. Traceback of forward call that caused the error:
  File "main.py", line 89, in <module>
    RETCODE = main()
  File "main.py", line 83, in main
    train_predictor()
  File "main.py", line 75, in train_predictor
    train_pred.run()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 121, in run
    self.__init_data()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 154, in _fit
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 230, in process_predictor_model
    predicted = self.predictor.model(self.__get_config_type(batch, self.config_type_pred_input))
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/utils/losses.py", line 13, in forward
    loss = torch.mean(((target - prediction) ** 2) * self.__weight(target))
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/_tensor.py", line 40, in wrapped
    return f(*args, **kwargs)
 (Triggered internally at ../torch/csrc/autograd/python_anomaly_mode.cpp:114.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    RETCODE = main()
  File "main.py", line 83, in main
    train_predictor()
  File "main.py", line 75, in train_predictor
    train_pred.run()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 121, in run
    self.__init_data()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 154, in _fit
    
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 233, in process_predictor_model
    if mode == TRAIN:
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/bletchkey/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function 'PowBackward0' returned nan values in its 0th output.
2024-03-26 21:46:48,520 - root - INFO - Training started at 26/03/2024 21:46:48
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    RETCODE = main()
  File "main.py", line 83, in main
    train_predictor()
  File "main.py", line 75, in train_predictor
    train_pred.run()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 122, in run
    self._fit()
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 177, in _fit
    self.__save_progress_plot(data)
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/TrainingPredictor.py", line 408, in __save_progress_plot
    save_progress_plot_dataset(data, self.current_epoch, self.__folders.results_folder)
  File "/home/bletchkey/ASGNTC/src/gol_adv_sys/utils/helper_functions.py", line 326, in save_progress_plot_dataset
    text_data += f"{k}: {plot_data[key][k][indices[i]]}\n"
IndexError: string index out of range
2024-03-26 22:02:58,469 - root - INFO - Training started at 26/03/2024 22:02:58
